### PR TITLE
Added Docker support to Capsule

### PR DESCRIPTION
**Pull request by lezwon**
Run capsule with `docker compose up`
Docker installs all requirements and configures redis and the zmq server
run the jupyter notebook locally to check execution

Other changes:
-- removed MPC 
--removed other unnecessary files
-- renamed build_and_run.sh to build_and_run_zmq.sh
-- fixed zmq `operation cannot be accomplished in current state` error
-- fixed deserialization errors

### CODE REVIEW

**Comment by iamtrask** [comment]
Hmm... travis seems to be hanging.

**Comment by anoff** [comment]
Checkpoints should be on `.gitignore` 🤕

**Review by iamtrask — APPROVED** [review]

**Comment by iamtrask** [comment]
hmmm - build still seems to be hanging - @bharathgs & @anoff

**Comment by aradhyamathur** [comment]
there seems to be a bug with forced update in travis at times they do show considerable lag. https://github.com/facebook/rocksdb/issues/2778

**Pull request closed without merging**
