### PR TITLE
Capsule SPDZ MPC

### PR DESCRIPTION
**Pull request by Devin97**
Capsule support for SPDZ

### CODE REVIEW

**Comment by iamtrask** [comment]
woot woot!

**Comment by iamtrask** [comment]
thanks for getting rid of the ipython notebook checkpoints too.

**Comment by Devin97** [comment]
gosh! about time.

**Comment by anoff** [comment]
Please squash commits with meaningful commit messages

**Comment by Devin97** [comment]
I just adjusted the code style for travis build

**Pull request closed without merging**
